# This is the recommended way of running Baserow using docker-compose for most users.
# See https://baserow.io/docs/installation%2Finstall-with-docker for more details.
version: "3.4"
services:
  baserow:
    container_name: baserow
    image: baserow/baserow:latest
    environment:
      BASEROW_PUBLIC_URL: 'https://baserow.automateme.ru'
    ports:
      - "80:8180"
      - "443:8143"
    volumes:
      - baserow_data:/baserow/data
volumes:
  baserow_data:
